
package GUI_Data;

import javax.swing.JOptionPane;
import java.util.regex.Pattern;
import java.sql.*;
import JavaClasses.DBConnection;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author GIGABYTE
 */
public class ChannelDoctor extends javax.swing.JFrame {
    
    Connection conn = null;
    Statement stmt = null;

    /**
     * Creates new form ChannelDoctor
     */
    public ChannelDoctor() {
        
        initComponents();
        conn = DBConnection.getconn();
        displayTable();
    }
    
    private void displayTable()
    {
        try
        {
            stmt = conn.createStatement();
            String sql = "SELECT * FROM patient";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            jPTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null, ee.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboSymptom = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        txtName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cboAmt = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 50, 204));
        jLabel1.setText("Channel a Doctor");

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel4.setText("Phone");

        cboSymptom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Back pain", "Leg pain", "Sinusitis", "Sore Throat", "Hand pain", "Influenza", "Fever" }));

        jLabel5.setText("Symptom");

        buttonGroup1.add(radMale);
        radMale.setSelected(true);
        radMale.setText("Male");

        buttonGroup1.add(radFemale);
        radFemale.setText("Female");

        jLabel6.setText("E-mail");

        btnSave.setIcon(new javax.swing.ImageIcon("F:\\NIBM\\EAD\\EADCourseWork2_KUDSE20.1F014\\resources\\diskette.png")); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("F:\\NIBM\\EAD\\EADCourseWork2_KUDSE20.1F014\\resources\\exchange.png")); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jPTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jPTable1);

        jLabel7.setText("Amount");

        cboAmt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rs.1000", "Rs.2000", "Rs.5000", "Rs.10000" }));

        btnBack.setIcon(new javax.swing.ImageIcon("F:\\NIBM\\EAD\\EADCourseWork2_KUDSE20.1F014\\resources\\previous.png")); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel8.setText("Patient ID");

        btnClear.setIcon(new javax.swing.ImageIcon("F:\\NIBM\\EAD\\EADCourseWork2_KUDSE20.1F014\\resources\\clear.png")); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radFemale)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radMale)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(btnSave)
                                        .addComponent(jLabel6)))
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radMale)
                            .addComponent(radFemale))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate)
                            .addComponent(btnClear))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure want to go back all the data will be lost", "Select Option",JOptionPane.YES_NO_OPTION);
        
        if(response == JOptionPane.YES_OPTION)
        {
            this.setVisible(false);
            new Patient().setVisible(true);
        }
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       String gender = null;
       String symptom = cboSymptom.getSelectedItem().toString();
       String pNum = txtPhone.getText();
       String PName = txtName.getText();
       String amount = cboAmt.getSelectedItem().toString();
        
       
       
       
            if(radMale.isSelected())
            {
                gender = "Male";
            }
            else if(radFemale.isSelected())
            {
                gender = "Female";
            }


        //Validations
            if(txtPatientID.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Patient ID is Required");
                txtPatientID.requestFocus();
                
            }
            else if(txtName.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Name is Required");
                txtName.requestFocus();
                
            }
            else if(txtAddress.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Address is Required");
                txtAddress.requestFocus();
               
            }
            else if(txtPhone.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Contact Number is Required");
                txtPhone.requestFocus();
                
            }
            else if(!Pattern.matches("^[0-9]+$", pNum))
            {
                JOptionPane.showMessageDialog(null, "Invalid Contact Number Format");
                txtPhone.setText("");
                txtPhone.requestFocus();
                
            }
            else
            {
                try
                {
                    stmt = conn.createStatement();
                    String sql = "INSERT INTO patient(PatientID,Name,Address,Phone,Symptom,Gender,Email,Amount)VALUES('"+txtPatientID.getText()+"', '"+txtName.getText()+"','"+txtAddress.getText()+"','"+pNum+"', '"+symptom+"','"+gender+"', '"+txtEmail.getText()+"', '"+amount+"')";
                    stmt.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Saved Successfully!");
                    
                    txtPatientID.setText("");
                    txtName.setText("");
                    txtAddress.setText("");
                    txtPhone.setText("");
                    txtEmail.setText("");
                    txtPatientID.requestFocus();
                    displayTable();
                }
                catch(Exception h)
                {
                    JOptionPane.showMessageDialog(null, h.toString());
                }
            }
        
            
    
           
       
      
       
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
                    txtPatientID.setText("");
                    txtName.setText("");
                    txtAddress.setText("");
                    txtPhone.setText("");
                    txtEmail.setText("");
                    txtPatientID.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        
       String gender = null;
       String symptom = cboSymptom.getSelectedItem().toString();
       String pNum = txtPhone.getText();
       String PName = txtName.getText();
       String amount = cboAmt.getSelectedItem().toString();
        
       
       
       
        if(radMale.isSelected())
        {
                gender = "Male";
        }
        else if(radFemale.isSelected())
        {
                gender = "Female";
        }
        if(txtPatientID.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter valid Patient ID to Update");
            txtPatientID.requestFocus();
        }
        else
        {
            try
            {
                stmt = conn.createStatement();
                String sql = "UPDATE patient SET PatientID = '"+txtPatientID.getText()+"' ,Name = '"+txtName.getText()+"', Address = '"+txtAddress.getText()+"', Phone = '"+pNum+"', Symptom = '"+symptom+"', Gender = '"+gender+"', Email = '"+txtEmail.getText()+"', Amount = '"+amount+"' WHERE PatientID = '"+txtPatientID.getText()+"' ";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Updated Successfully!");
                    txtPatientID.setText("");
                    txtName.setText("");
                    txtAddress.setText("");
                    txtPhone.setText("");
                    txtEmail.setText("");
                    txtPatientID.requestFocus();
                    displayTable();
                
                
                
            }
            catch(Exception h)
            {
                JOptionPane.showMessageDialog(null, h.toString());
            }
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChannelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChannelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChannelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChannelDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChannelDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboAmt;
    private javax.swing.JComboBox<String> cboSymptom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTable jPTable1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
